apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-mongo.fullname" . }}
  labels:
{{ include "helm-mongo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort}}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm-mongo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
